#!/usr/bin/env python3

import os
import platform

# Standardized Python Version
PYTHON_VERSION = "python{}.{}".format(*(platform.python_version_tuple()[:2]))

THIS_DIR = os.path.abspath(os.path.dirname(__file__))

REPOSITORY_FOLDER = os.path.abspath(os.path.join(THIS_DIR, ".."))

VENV_FOLDER = os.path.join(REPOSITORY_FOLDER, ".venv")
VENV_BIN_FOLDER = os.path.join(VENV_FOLDER, "bin")
VENV_SITEPACKAGES_FOLDER = os.path.join(VENV_FOLDER, "lib", PYTHON_VERSION, "site-packages")

def replace_macros(template_line):
    """
        Perform a simple replacement any macros found in the template line passed to us.
    """

    home = os.path.expanduser("~")

    filled_line = template_line

    filled_line = filled_line.replace(r"${TMPLT:HOME}", home)
    filled_line = filled_line.replace(r"${TMPLT:PYTHON_VERSION}", PYTHON_VERSION)
    filled_line = filled_line.replace(r"${TMPLT:REPOSITORY_FOLDER}", REPOSITORY_FOLDER)
    filled_line = filled_line.replace(r"${TMPLT:VENV_FOLDER}", VENV_FOLDER)
    filled_line = filled_line.replace(r"${TMPLT:VENV_BIN_FOLDER}", VENV_BIN_FOLDER)
    filled_line = filled_line.replace(r"${TMPLT:VENV_SITEPACKAGES_FOLDER}", VENV_SITEPACKAGES_FOLDER)

    return filled_line

def generate_devemopment_env_file():

    cache_dir = os.path.join(REPOSITORY_FOLDER, ".cache")
    if not os.path.exists(cache_dir):
        os.makedirs(cache_dir)

    dev_env_file = os.path.join(cache_dir, "development.env")
    with open(dev_env_file, 'w') as envf:
        envf.write("PYTHONPATH={}/testroots:{}/packages:{}".format(
            REPOSITORY_FOLDER,
            REPOSITORY_FOLDER,
            VENV_SITEPACKAGES_FOLDER
        ))
        envf.write(os.linesep)

        #TODO: Add the setting of any other 'development.env' environment variables here.

        envf.write(os.linesep)

    return

def generate_vscode_workspace_files():
    # Go through all of the VSCODE workspace templates and generate the 'code-workspace' files homed to the
    # location of this cloned repository

    template_file = os.path.join(REPOSITORY_FOLDER, "apod.template")
    workspace_file = os.path.join(REPOSITORY_FOLDER, "apod.code-workspace")

    print("Convereting Workspace Template:")
    print(template_file)
    print("")

    with open(template_file, 'r') as tf:
        template_lines = tf.read().splitlines(True)

        with open(workspace_file, 'w') as wf:
            print("Generating code-workspace: {}".format(workspace_file))
            for tline in template_lines:
                fline = replace_macros(tline)
                wf.write(fline)
    
    return

def rehome_repository_main():

    generate_devemopment_env_file()
    generate_vscode_workspace_files()

    return

if __name__ == "__main__":
    rehome_repository_main()
